kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: openshift-gitops
type: Opaque
stringData:
  AVP_AUTH_TYPEar: k8s
  AVP_K8S_ROLE: vplugin
  AVP_TYPE: vault
  VAULT_ADDR: http://172.30.137.242:8200
