kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: openshift-gitops
type: Opaque
stringData:
  AUTH_TYPE: k8s
  K8S_ROLE: vplugin
  TYPE: vault
  VAULT_ADDR: http://172.30.137.242:8200
